Add Programmer's Notepad
reactos/rapps-db pull request #124
Opened 2020-10-02 15:25 UTC by chirsz-ever

2020-10-02 15:46 UTC, HBelusca requested changes
Can you show us an example that proves that this application works fine in ReactOS?

2020-10-02 16:05 UTC, chirsz-ever commented
![VirtualBox_ReactOS-0 4-2010030004](https://user-images.githubusercontent.com/31474766/94944625-18473b80-050c-11eb-923a-356392824a9e.png)

2020-10-02 20:52 UTC, learn-more approved these changes

2020-10-02 20:53 UTC, HBelusca approved these changes

2020-10-02 20:56 UTC, learn-more commented on pnotepad.txt
> +Size = 2.4 MiB
Size not needed.

2021-06-05 12:19 UTC, merged

2021-06-05 12:20 UTC, learn-more commented
Thanks for your contribution, sorry for the delay!