Massive update for Italian language
reactos/rapps-db pull request #129
Opened 2020-10-24 18:22 UTC by davi92

- Massive update for Italian language for all application
- Fix language code for support Italian Switzerland(it-CH), Italian San marino(it-SM) and Italian Vatican (it-VA)

2020-10-24 18:26 UTC, binarymaster commented
Cc @reactos/lang-italian something massive here, need review.

2020-10-24 18:28 UTC, binarymaster requested changes
Please fix line-endings changes to make the diff look normal.

2020-10-25 09:20 UTC, ElCresh commented on BOINC.txt
>  Description = BOINC è una piattaforma software open source per l'elaborazione che utilizza risorse volontarie.
I think is bettere to emphatize with "elaborazione distribuita"

2020-10-25 09:28 UTC, ElCresh commented on ac97forvirtualbox.txt
> +Description = Driver audio per dispositivi compatibili con AC'97. Decomprimere nella cartella ReactOS e riavviare due volte.
I think should be maintained as "ReactOS" (with quotes) ora << ReactOS>> like in spanish translation.

2021-06-02 09:42 UTC, GeoB99 commented
@davi92 Do you plan to continue work on this, since the PR is still draft? I plan to take it for a review someday.

2021-06-02 12:54 UTC, learn-more commented
I'd say in it's current state this is not reviewable.

2021-06-02 18:42 UTC, davi92 commented
> @davi92 Do you plan to continue work on this, since the PR is still draft? I plan to take it for a review someday.

    I tried to convert the files to the required format, but as soon as I load them github treats them as binary files.
Sorry for bad english.

2021-09-16 08:21 UTC, learn-more commented
Loads of bogus files, and no update from author.

2021-09-16 08:21 UTC, closed without merging