LibreOffice update
reactos/rapps-db pull request #146
Opened 2021-09-05 21:58 UTC by d1nuc0m

- Divided LibreOffice in Fresh and Still branches 
- Updated Still to latest version working on ReactOS (tested on ROS 0.14.3 on VirtualBox 6.1.x)
- Updated URLs and descriptions

2021-09-06 14:01 UTC, learn-more reviewed
Thanks for taking the time to update this!

I think that adding 'fresh' to the name is only going to confuse people, since this is not a very common term for software.

2021-09-06 14:44 UTC, d1nuc0m commented on libreofficefresh.txt
> +Name = LibreOffice Fresh
It is a LibreOffice convention, LibreOffice Fresh is the more up-to-date branch (in this moment it is 7.2.x), more functions but more prone to bugs; LibreOffice Still is a more stable branch (in this moment it is 7.1.x), slightly behind Fresh version, but more robust.
I have checked the latest Fresh and Still branches that work on ReactOS, and are respectively 5.4.x and 5.3.x

2021-09-06 14:45 UTC, d1nuc0m commented on libreofficestill.txt
> +Size = 210 MiB
Thank you, where can I find a complete list of available and required fields? The wiki and this repository seem to be missing some details

2021-09-06 15:34 UTC, binarymaster commented on libreofficestill.txt
> +Size = 210 MiB
See https://reactos.org/wiki/RAPPS

2021-09-08 21:10 UTC, d1nuc0m commented on libreofficefresh.txt
> +Name = LibreOffice Fresh
@learn-more Fresh/Still difference has also been discussed [on LibreOffice forums](https://ask.libreoffice.org/t/what-is-the-difference-between-libreofficefresh-and-libreofficestill/18684), same for [compatibility with x86 XP/2003](https://ask.libreoffice.org/t/whats-latest-ver-i-can-use-on-my-32bit-xp-sp3-machines/24434/2)

2021-09-08 21:16 UTC, JoachimHenze requested changes
Requested change: We currently have 2 LibreOffice versions already in ros.
**We should delete one, and keep (+update) only one of them.**

**Ofc only after testing whether the new version works well on 2k3sp2 and in ros. Please post screenshots that prove both for the version that you suggest here.**

I do also contribute something: the proof by previous tests that both of our outdated existing versions do run in a comparable manner: search for "LibreOffice" in https://reactos.org/wiki/Tests_for_0.4.14
I spotted 16bugs quickly in both. They do behave almost identically. A waste of time to always test 2 versions for each release.

2021-09-09 10:11 UTC, d1nuc0m commented
> 
> 
> Requested change: We currently have 2 LibreOffice versions already in ros.
> **We should delete one, and keep (+update) only one of them.**
> 
> **Ofc only after testing whether the new version works well on 2k3sp2 and in ros. Please post screenshots that prove both for the version that you suggest here.**
> 
> I do also contribute something: the proof by previous tests that both of our outdated existing versions do run in a comparable manner: search for "LibreOffice" in https://reactos.org/wiki/Tests_for_0.4.14
> I spotted 16bugs quickly in both. They do behave almost identically. A waste of time to always test 2 versions for each release.

Actually one of the two versions in ROS is already the latest that can run on XP/2003/Vista (Libreoffice 5.4.7.2).

I proposed to update the other one because 5.1.x is outdated if we consider that the last two branches of LibreOffice that supported XP/2003/Vista are 5.3.x and 5.4.x.

I think there are two version because of the Fresh/Still categorization of versions, but if only one should be kept, I would suggest to keep 5.4.7.2, as it is the last that can run on ROS and has already been tested (it's listed in the page you linked).

Just in case it might be needed, here is a screenshot of LibreOffice 5.3.7.2 on ReactOS 0.4.13 on Virtualbox 6.1.22 with Guest Additions and 3096 MB of RAM. 

![ROS_LO](https://user-images.githubusercontent.com/72998205/132666196-3a9f4a2e-971f-439f-bc78-f645a51014ab.png)

2021-09-09 16:26 UTC, JoachimHenze commented
So we are at latest&greatest for our target already. Fine then.
Well then it's possible to delete the older one (5.1.1.3) just, if you want to update the PR for that. Otherwise we should just close this PR. I see no urgent need for any of the changes in libreoffice.txt.

2021-09-09 21:59 UTC, d1nuc0m commented
@JoachimHenze updated the pull request.
Out of curiosity, why is there the CDPath parameter in LibreOffice file? (It is not documented in the wiki)

2021-09-13 17:32 UTC, d1nuc0m commented
Probably not useful

2021-09-13 17:32 UTC, closed without merging