Add Mario & Luigi game
reactos/rapps-db pull request #228
Opened 2024-03-08 23:13 UTC by marjuanm

Mario Bros fangame that works under MS-DOS, in versions of Windows 9x it works without problems, in Windows XP I haven't had the opportunity to try it, but in more recent versions of Windows it only works from DosBox, but in Reactos it works perfectly.

2024-03-08 23:15 UTC, marjuanm commented
DOS game running on Reactos directly:
![Screenshot_1](https://github.com/reactos/rapps-db/assets/30614131/4f8cf12d-e296-4957-bcb5-01524fc64c82)
![Screenshot_2](https://github.com/reactos/rapps-db/assets/30614131/f2be5671-fc60-467c-8135-c4bf9148b057)
![Screenshot_3](https://github.com/reactos/rapps-db/assets/30614131/13996f80-cb3d-497f-8179-cda0a900e37c)
![Screenshot_4](https://github.com/reactos/rapps-db/assets/30614131/65d61478-363a-4ddc-8885-62238ec04f68)

2024-03-19 10:17 UTC, learn-more commented
@marjuanm you have both games in this PR now.

Please create a branch per pull request, because new pushes to a branch with an open pull request end up in that PR.

2024-05-31 11:56 UTC, JoachimHenze commented
yes, agwak shouldn't be in here.

2024-06-04 15:50 UTC, marjuanm commented
deleted incorrect files in this game

2024-06-06 09:40 UTC, learn-more approved these changes

2024-06-30 02:32 UTC, katahiromz requested changes
One request for one pull request.

2024-06-30 02:38 UTC, katahiromz requested changes

2024-06-30 02:38 UTC, katahiromz commented on icons/icon.ico
What's this icon?

2024-06-30 03:19 UTC, katahiromz approved these changes
Tests successful. LGTM.

2024-06-30 14:19 UTC, merged