Add Safari 5.1.7
reactos/rapps-db pull request #255
Opened 2024-07-10 15:05 UTC by Usinganame

Safari 5.1.7 is the latest version of Safari to support Windows

2024-07-10 15:48 UTC, binarymaster commented on safari.txt
> +License = EULA
```suggestion
License = EULA
LicenseType = 2
```
https://reactos.org/wiki/RAPPS#LicenseType

2024-07-10 15:48 UTC, binarymaster commented on safari.txt
> +Description = Apple Safari for Windows version 5.1.7
```suggestion
Description = Apple Safari browser for Windows.
```
As the version is already in the other field.

2024-07-10 15:48 UTC, binarymaster commented on safari.txt
> +Icon = safari.ico
You can omit this field, as the icon filename matches the txt filename.

https://reactos.org/wiki/RAPPS#Icon

```suggestion
```

2024-07-10 15:48 UTC, binarymaster commented on safari.txt
> +SizeBytes = 38494576
Would be nice to add SHA1 checksum here.

https://reactos.org/wiki/RAPPS#SHA1

2024-07-11 10:42 UTC, binarymaster reviewed
Have you tested it in ReactOS? For me it installs, but runs unbelievably slow (barely usable).

![VirtualBox_ReactOS_11_07_2024_13_37_58](https://github.com/reactos/rapps-db/assets/578406/5a8d9630-26b9-4995-b582-62136481b58e)

2024-07-11 16:13 UTC, Usinganame commented
I have tested it, but it was under VirtualBox and as i can't install the necessary drivers it runs slow either way and i don't have a spare computer laying around. I just assumed that it was slow either way, like Chromium or Mypal

2024-07-24 10:20 UTC, JoachimHenze requested changes
It runs unbearably slow due to existing bugs in ReactOS. That has nothing to do with the VBox emulation.
Since our common practice is to only add applications to rapps that are known to work in an acceptable manner, I do suggest not merging this PR until somebody would be able to name at least one website, which can only be opened by this browser, but not a single other available browser option for ros.
Either that, or we should wait with the merging until the slowness-bug in ros will have been fixed already.
I don't see much use in adding a lot of applications into rapps, that don't work well yet.

The last bug that we (think we) fixed in Safari-context was https://jira.reactos.org/browse/CORE-13125 but that doesn't deal specifically with the slowness. If there is not a slowness-bug filed in JIRA already that I missed, then that should be created **now** and be linked here in this conversation.

2024-08-22 17:28 UTC, closed without merging