Add Core Temp 1.18.1
reactos/rapps-db pull request #267
Opened 2024-09-05 10:45 UTC by scropool

2024-09-05 11:48 UTC, vsaucing approved these changes

2024-09-05 17:21 UTC, learn-more approved these changes

2024-09-05 18:20 UTC, julenuri requested changes

2024-09-05 18:23 UTC, julenuri approved these changes

2024-09-05 18:30 UTC, julenuri commented
I like this software under rapps-db.

Bad thing, to not have the x64 version in the PR. To be added in the future.  @scropool ?

2024-09-06 09:54 UTC, scropool commented on CoreTemp.txt
> +Icon = coretemp.ico
I will take your suggestion seriously

2024-09-06 09:56 UTC, scropool commented on CoreTemp.txt
> +Icon = coretemp.ico
> I would delete this line and change the name of the .ico to be the same of the txt.

what about the icon file? won't it be there?

2024-09-06 09:57 UTC, scropool commented
> I like this software under rapps-db.
> 
> Bad thing, to not have the x64 version in the PR. To be added in the future. @scropool ?

reactos only runs 64 bit applications with .msi extension so if coretemp works I can add it

2024-09-06 10:24 UTC, scropool commented
> I like this software under rapps-db.
> 
> Bad thing, to not have the x64 version in the PR. To be added in the future. @scropool ?

![image](https://github.com/user-attachments/assets/9b1e2131-1257-4fff-9cee-c211086d233f)
x64 version is now working with portable zip edition

2024-09-06 18:49 UTC, merged